describe('add to cart', () => {
  it('register new user', () => {
    cy.visit('http://localhost:3000')
    cy.wait(3000)
    cy.get('a').contains('Register').click()
    cy.wait(2000)
    const email = `test-${(Math.random() * 1000).toFixed()}@example.com`
    cy.get('#email').type(email)
    cy.get('#password').type('vbhv3301')
    cy.get('#firstName').type('John')
    cy.get('#lastName').type('Doe')
    cy.get('button').contains('Create an account').click()
    cy.get('a').contains('Sign in').click()
    cy.wait(2000)
    cy.get('#email').type(email)
    cy.get('#password').type('vbhv3301')
    cy.get('button').contains('Log In').click()
    cy.get('button').contains('Add to Cart').click()
    cy.get(':nth-child(1) > .flex.gap-2 > .justify-between > .rounded-r-full').click()
    cy.get(':nth-child(1) > .flex.gap-2 > .justify-between > .rounded-r-full').click()
    cy.get(':nth-child(1) > .flex.gap-2 > .justify-between > .rounded-r-full').click()
    cy.get(':nth-child(1) > .flex.gap-2 > .justify-between > .rounded-l-full').click()
    cy.get(':nth-child(1) > .flex.gap-2 > .justify-between > .rounded-r-full').click()
    cy.get('[aria-haspopup="dialog"] > .justify-center').click()
    cy.contains('$439.80').should('exist')
  });
})