version: "3.6"
services:
  postgres:
    image: postgres:latest
    container_name: se_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_simple_ecom_v1:/var/lib/postgresql/data
    env_file:
      - ./config/.env

volumes:
  db_simple_ecom_v1:
